# Nome do projeto
spring.application.name=inventario

# --- CONFIGURAÇÃO DO BANCO DE DADOS ---
# Onde o banco mora: (localhost), porta (3306) e nome da gaveta (inventario)
spring.datasource.url=jdbc:mysql://localhost:3306/inventario?useTimezone=true&serverTimezone=UTC

# Login e Senha
spring.datasource.username=root
spring.datasource.password=Gui.300106@!

# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# -- COMPORTAMENTO DO JPA (HIBERNATE) --- 
# "update": Ao criar uma classe Java nov, ele cria a tabela no banco automaticamente.
# Se a tabela já existir, ele só atualiza. Não apaga seus dedos!
spring.jpa.hibernate.ddl-auto=update

# Mostra no terminal o SQL que o Java está fazendo (bom para aprender/debugar)
spring.jpa.show-sql=true

# Ativa a importação automática de computadores e impressoras na inicialização
importar=true